package mocks

import (
	"context"
	"erp-system/internal/inventory/models"
	"erp-system/internal/inventory/repository"

	"github.com/google/uuid"
	"github.com/stretchr/testify/mock"
)

// ItemRepository is an autogenerated mock type for the ItemRepository type
type ItemRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, item
func (_m *ItemRepository) Create(ctx context.Context, item *models.Item) (*models.Item, error) {
	ret := _m.Called(ctx, item)

	var r0 *models.Item
	if rf, ok := ret.Get(0).(func(context.Context, *models.Item) *models.Item); ok {
		r0 = rf(ctx, item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Item)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.Item) error); ok {
		r1 = rf(ctx, item)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ItemRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *ItemRepository) GetByID(ctx context.Context, id uuid.UUID) (*models.Item, error) {
	ret := _m.Called(ctx, id)

	var r0 *models.Item
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Item); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Item)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBySKU provides a mock function with given fields: ctx, sku
func (_m *ItemRepository) GetBySKU(ctx context.Context, sku string) (*models.Item, error) {
	ret := _m.Called(ctx, sku)

	var r0 *models.Item
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Item); ok {
		r0 = rf(ctx, sku)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Item)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, sku)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, offset, limit, filters
func (_m *ItemRepository) List(ctx context.Context, offset int, limit int, filters map[string]interface{}) ([]*models.Item, int64, error) {
	ret := _m.Called(ctx, offset, limit, filters)

	var r0 []*models.Item
	if rf, ok := ret.Get(0).(func(context.Context, int, int, map[string]interface{}) []*models.Item); ok {
		r0 = rf(ctx, offset, limit, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Item)
		}
	}

	var r1 int64
	if rf, ok := ret.Get(1).(func(context.Context, int, int, map[string]interface{}) int64); ok {
		r1 = rf(ctx, offset, limit, filters)
	} else {
		r1 = ret.Get(1).(int64) // Make sure this is correct based on your actual mock needs
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, int, int, map[string]interface{}) error); ok {
		r2 = rf(ctx, offset, limit, filters)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Update provides a mock function with given fields: ctx, item
func (_m *ItemRepository) Update(ctx context.Context, item *models.Item) (*models.Item, error) {
	ret := _m.Called(ctx, item)

	var r0 *models.Item
	if rf, ok := ret.Get(0).(func(context.Context, *models.Item) *models.Item); ok {
		r0 = rf(ctx, item)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Item)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *models.Item) error); ok {
		r1 = rf(ctx, item)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewItemRepository creates a new instance of ItemRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewItemRepositoryMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ItemRepository {
	mock := &ItemRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

var _ repository.ItemRepository = (*ItemRepository)(nil)
